{{- if gt .Values.replicas 1.0 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: scylla-operator
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "scylla-operator.selectorLabels" . | nindent 6 }}
{{- end }}
